config/routes.rb
Rails.application.routes.draw do
  # get '/' => 'users#index'
  root 'users#index'

  resources :users, only: [:index, :create, :show]

  get '/signup' => 'users#new', as: 'new_user'
  get '/login' => 'sessions#new', as: 'login'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/libraries' => 'libraries#index', as: 'libraries'
  get '/libraries/new' => 'libraries#new', as: 'new_library'
  post '/libraries' => 'libraries#create'

  get '/users/:user_id/libraries' => 'library_users#index', as: 'user_libraries'
  post '/libraries/:library_id/users' => 'library_users#create', as: 'library_users'
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :library_users
  has_many :users, through: :library_users
end

app/models/library_user.rb
class LibraryUser < ApplicationRecord
  belongs_to :user
  belongs_to :library
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :library_users
  has_many :libraries, through: :library_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

  def index
    @libraries = Library.all
  end

  def new
  end

  def create
    library = Library.create(
      name: params[:name],
      floor_count: params[:floor_count],
      book_count: params[:book_count]
    )
    redirect_to libraries_path
  end

end

app/controllers/library_users_controller.rb
class LibraryUsersController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @libraries = @user.libraries
  end

  def create
    user = current_user
    library = Library.find(params[:library_id])
    user.libraries.push(library)

    redirect_to user_libraries_path(user)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      login(user)
      redirect_to user_path(user)
    else
      redirect_to login_path
    end
  end

  def destroy
    logout
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all
  end

  def new
    render :new #optional, default behavior
  end

  def create
    user = User.create(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password]
    )
    login(user) #login our user after creating
    redirect_to user_path(user) #go to show page
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/library_users_helper.rb
module LibraryUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/libraries/index.html.erb
<h1>All Libraries</h1>

<% @libraries.each do |library| %>
  <div>
    <h2><%= library.name %></h2>
    
    <% if current_user %>
      <%= button_to "Join", library_users_path(library) %>
    <% end %>

  </div>
  <br>
<% end %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= form_tag "/libraries", method: :post do %>
  <div>
    <%= text_field_tag :name, nil, placeholder: "Name" %>
  </div>
  <div>
    <%= number_field_tag :floor_count, nil, placeholder: "Floor Count" %>
  </div>
  <div>
    <%= number_field_tag :book_count, nil, placeholder: "Book Count" %>
  </div>
  <%= submit_tag "Add Library" %>
<% end %>

app/views/library_users/index.html.erb
<div><%= @user.first_name %> is a member of the following libraries:</div>

<ul>
  <% @libraries.each do |library| %>
    <li><%= library.name %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1>Users Index</h1>

<div>
  There are currently <%= @users.count %> users signed up.
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_tag '/users', method: :post do %>
  <div>
    <%= text_field_tag :first_name, nil, placeholder: "First Name" %>
  </div>
  <div>
    <%= text_field_tag :last_name, nil, placeholder: "Last Name" %>
  </div>
  <div>
    <%= text_field_tag :email, nil, placeholder: "Email" %>
  </div>
  <div>
    <%= password_field_tag :password, nil, placeholder: "Password" %>
  </div>
  <%= submit_tag "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<div>
  Welcome, <%= @user.first_name %>
</div>